### ISSUE TITLE
Upload repository to maven

### ISSUE THREAD

**Issue by Erellariss** [ChibiTomo/ApiVersioning#11]
Hello! Can you upload your repository to maven? I can't find him.

**Comment by ChibiTomo** [comment]
Hi. I had first some difficulties to release to maven, but now it's ok. You should be able to find it.

```xml
<dependency>
  <groupId>net.chibidevteam</groupId>
  <artifactId>apiversioning</artifactId>
  <version>0.1.0</version>
</dependency>
```
